### ISSUE TITLE
Добавить поддержку тайм-кодов и изменить лицензию

### ISSUE THREAD

**Issue by egorsmkv** [zoonru/commonmark-ext-youtube-iframe#1]
Привет!

Вы сделали полезную бибилотеку, спасибо!

У меня два вопроса:

1. Иногда люди отправляют ссылки с тайм-кодами. Например, https://www.youtube.com/watch?time_continue=100&v=mVnSpPMgoWM . Добавить в бибилотеку это не сложно и будет полезно. 
2. Возможно ли изменить лицензию на MIT?

**Comment by sergkash7** [comment]
Привет, готово! 😉

**Comment by egorsmkv** [comment]
Круто! Спасибо!
